Timeslot
McGill-ECSE321-Winter2021/project-group-09 pull request #101
Opened 2021-03-06 07:17 UTC by JDziewonski98

getall, getbyid, create logic all tested

2021-03-06 14:07 UTC, sandyl289 requested changes
I think we should add one more test to test an invalid input for GetTimeslot(), other than that, everything looks good!

2021-03-06 14:07 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestTimeSlotService.java
> +
I think we are also required to test invalid inputs. I tried to write a test, but it failed.

The test I wrote:
```
@Test
  public void testGetTimeslotNonExistent() {
        String error = null;
        Long nonExistentTimeSlotID = 9999l;

        try {
            timeSlotService.getTimeslotByID(nonExistentTimeSlotID);


        } catch (Exception e) {
            error = e.getMessage();
        }
        assertEquals("Timeslot not found", error);
    }
```

2021-03-06 14:07 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/TimeSlotController.java
> +            return new ResponseEntity<>(timeSlotService.createTimeslot(timeslot), HttpStatus.OK);
Just a question: When do we need to use `HttpsStatus.CREATED`?

2021-03-06 14:24 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestTimeSlotService.java
> +
Error I get when I add the test I wrote (`testGetTimeslotNonExistent()`)<br/>
![image](https://user-images.githubusercontent.com/70775435/110209302-b0e63c80-7e59-11eb-832b-22fe4e9dfc80.png)

2021-03-06 14:47 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestTimeSlotService.java
> +        assertEquals(ID, timeslot.getID()); // List contains the only comment.
```suggestion
        assertEquals(ID, timeslot.getID()); 
```

2021-03-06 15:09 UTC, T-Syme commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestTimeSlotService.java
> +
It looks like it's caused by the Optional<TimeSlot> part
![image](https://user-images.githubusercontent.com/70815823/110211317-10494a00-7e64-11eb-8f71-cc6d4f8b2ed8.png)

2021-03-06 15:17 UTC, T-Syme reviewed
I agree with Sandy's suggestions. Apart from those, all looks good to me

2021-03-06 15:21 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/TimeSlotController.java
> +            return new ResponseEntity<>(timeSlotService.createTimeslot(timeslot), HttpStatus.OK);
I'm not sure... If anywhere, this seems like the right place from this (although OK definitely fits too):
![image](https://user-images.githubusercontent.com/70815823/110211659-9c0fa600-7e65-11eb-9345-e806745e11bb.png)

2021-03-07 06:26 UTC, Shaswata79 approved these changes

2021-03-07 08:15 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/TimeSlotController.java
> +            return new ResponseEntity<>(timeSlotService.createTimeslot(timeslot), HttpStatus.OK);
yeah this would be the right time to do created

2021-03-07 22:51 UTC, merged