Made some changes to technician and customer service and controller. Added javadoc.
McGill-ECSE321-Winter2021/project-group-09 pull request #102
Opened 2021-03-06 08:20 UTC by Shaswata79

2021-03-06 16:25 UTC, sandyl289 requested changes
Added a suggestion for the documentation `@return` 
Other than that, everything looks good! I think you can merge it to `main`  💯

2021-03-06 16:25 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/TechnicianController.java
> +	 * @return
```suggestion
	 * @return status of deletion
```

2021-03-06 18:20 UTC, T-Syme reviewed
It might be best to add a short description to some of the methods in the Javadoc, even if it is as simple as "Method to create a customer" for the createCustomer method. I think it would improve the consistency. Apart from that everything looks ready to merge!

2021-03-07 08:16 UTC, JDziewonski98 approved these changes

2021-03-07 14:45 UTC, closed without merging