admin, appointment, technician dto classes modifications/additions
McGill-ECSE321-Winter2021/project-group-09 pull request #106
Opened 2021-03-07 01:38 UTC by zhannaklimanova

admin  + appointment dto classes added, technician dto class modified to account for updated uml class diagram

2021-03-07 01:47 UTC, T-Syme reviewed
All of the changes look good, although I don't think this should be merged until all associated code is modified or implemented

2021-03-07 02:00 UTC, sandyl289 requested changes
I think we need to add appointmentID other than that everything looks good!

![image](https://user-images.githubusercontent.com/70775435/110226612-dc4f4280-7ebe-11eb-983e-b759438c3359.png)

2021-03-07 02:00 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/AppointmentDto.java
```suggestion

private Long appointmentID;
```

2021-03-07 02:00 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/AppointmentDto.java
> +
```suggestion
    
    public Long getAppointmentID() {
        return this.appointmentID;
    }
    
    public void setAppointmentID(Long aAppointmentID) {
        this.appointmentID = aAppointmentID;
    }	
```

2021-03-07 02:03 UTC, zhannaklimanova commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/AppointmentDto.java
I wasn't sure about that, b/c we aren't actually  passing appointment id back and forth from ui to backend.? But I  am not sure abt  this either.

2021-03-07 06:21 UTC, Shaswata79 requested changes

2021-03-07 06:21 UTC, Shaswata79 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/TechnicianDto.java
> +	public void setAppointments(List<AppointmentDto> appointments) {
If there is already an association from AppointmentDto to TechnicianDto we cannot have an association from TechnicianDto to AppointmentDto. This would cause an infinite recursion of set methods (setTechnician and setAppointments).

2021-03-07 22:56 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/AdminService.java
> +		if(adminRepository.findAdminByEmail(email) == null) {
duplicate database queries are always good to avoid (here and line 154)

2021-03-07 22:57 UTC, JDziewonski98 approved these changes

2021-03-08 18:48 UTC, T-Syme approved these changes
Once Shaswata's suggestion is implemented, I think this should be good to merge

2021-03-09 06:45 UTC, zhannaklimanova commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/AdminService.java
> +		if(adminRepository.findAdminByEmail(email) == null) {
oh you mean where I accidentally  put email  == null twice?

2021-03-09 06:47 UTC, zhannaklimanova commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/TechnicianDto.java
> +	public void setAppointments(List<AppointmentDto> appointments) {
Ok, I'll look into it and remove

2021-03-12 02:53 UTC, merged

2021-03-12 02:58 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/AdminService.java
> +		if(adminRepository.findAdminByEmail(email) == null) {
(I know this was merged, just to respond to the question)

It wasn't so much for the "email == null" twice part (though that should change), but because the line "adminRepository.findAdminByEmail(oldEmail)" is repeated twice (and calls the database both times)