implemented cancelling an app
McGill-ECSE321-Winter2021/project-group-09 pull request #115
Opened 2021-03-12 04:30 UTC by JDziewonski98

Cancelling appointment by ID

2021-03-12 13:42 UTC, T-Syme approved these changes

2021-03-12 13:42 UTC, T-Syme commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAppointmentService.java
> +    private Appointment createAppointment(Long id) {
I'm guessing this is temporary since there's another createAppointment method on the book-appointment branch?

2021-03-12 15:01 UTC, sandyl289 requested changes
Left some comments (see below)

2021-03-12 15:01 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/AppointmentService.java
> +
Do we also need to do some checks here to make sure that we are 7 days before the appointment?
=> See [Use Case: Cancel Appointment](https://github.com/McGill-ECSE321-Winter2021/project-group-09/wiki/Detailed-Use-Cases#use-case-cancel-appointment) or see screenshot below

I don't know if it will be useful, but I already wrote some methods to get the system's current date and to add or subtract a certain number of days to a Timestamp (see [SystemTime.java on main branch](https://github.com/McGill-ECSE321-Winter2021/project-group-09/blob/main/RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/utilities/SystemTime.java))

- [systemDate()](https://github.com/McGill-ECSE321-Winter2021/project-group-09/blob/8b1a666bdfe402512bf284675edd607bd714e555/RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/utilities/SystemTime.java#L8-L16): Gets current system date. Return: `String` in the format YYYY-MM-DD. (TIME is NOT taken into account)
- [addOrSubtractDays()](https://github.com/McGill-ECSE321-Winter2021/project-group-09/blob/8b1a666bdfe402512bf284675edd607bd714e555/RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/utilities/SystemTime.java#L18-L30): Add or subtract a number of days to a timestamp. Return: `Timestamp` (TIME is taken into account)

![image](https://user-images.githubusercontent.com/70775435/110953897-dcfc3480-8315-11eb-87db-ccd2e4ccbbec.png)

2021-03-12 15:01 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAppointmentService.java
> +
If we don't allow the customer to cancel an appointment within 7 days before the appointment date, we might need to do some invalid cancel appointment tests here.

2021-03-12 16:07 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/AppointmentService.java
> +
I'm also adding some code to SystemTime.java so that we can get a Timestamp of the current date and time OR for a particular test date for use while we're testing everything

2021-03-12 21:53 UTC, JDziewonski98 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAppointmentService.java
> +    private Appointment createAppointment(Long id) {
There is 0 way I could have known

2021-03-12 23:57 UTC, T-Syme approved these changes

2021-03-13 02:39 UTC, sandyl289 approved these changes

2021-03-13 02:40 UTC, merged