Checkout testDeleteAdmin() method; not sure if it should be implemented at all given mock deletion might not be possible
McGill-ECSE321-Winter2021/project-group-09 pull request #124
Opened 2021-03-13 21:05 UTC by zhannaklimanova

TestAdminService class added; TestCustomerService + TestTechnicianService redundant object creation removed, AdminDto cleaned up

2021-03-13 21:43 UTC, T-Syme commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAdminService.java
> +
`adminRepo.deleteByCustomerEmail(email)` should probably be mocked too

Edit: I might have been wrong about this. I don't know if it can be mocked

2021-03-13 21:49 UTC, T-Syme approved these changes
Left a comment about a mock that shouldn't really have an impact. Also, I'm not sure about the changes to `testCreateTechnicianDuplicate()` and the customer version, but as long as it works...

2021-03-14 03:11 UTC, sandyl289 requested changes
- We should remove `@Transaction` over the `adminToDTO()` method
- I put some suggestions, you can ignore them if you want
Other than that, everything seems good 👍

2021-03-14 03:11 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/AdminService.java
>  	@Transactional
```suggestion
```
This is causing an error. We don't need to put `@Transactional` over this method.

![image](https://user-images.githubusercontent.com/70775435/111055550-e89a4900-8444-11eb-8b42-03ae06ba7633.png)

2021-03-14 03:11 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAdminService.java
> +
```suggestion
		assertNotNull(admin);
		assertEquals(adminName, admin.getName());
		assertEquals(adminEmail, admin.getEmail());
		assertEquals(adminPhone, admin.getPhoneNumber());
		assertEquals(adminAddress, admin.getAddress());
```

2021-03-14 03:11 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAdminService.java
> +	}
```suggestion
	@Test
	public void testChangePhoneNonExistentAdmin() {
				
		try {
			adminService.changePhone("nonExistentAdmin@nonExistentEmail.com", "somebody's phone");
			fail();
		} catch (Exception e) {
			//error should occur
			assertEquals("Admin not found.", e.getMessage());
		}
	}
```

2021-03-14 03:11 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAdminService.java
> +	public void testChangeNamelNull() {
Not really important, but there's an extra "l" between Name & Null

```suggestion
	public void testChangeNameNull() {
```

2021-03-14 03:11 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAdminService.java
> +			adminService.changeName("No One", "Some One");
```suggestion
			adminService.changeName("NoOne@gmail.com", "Some One");
```

2021-03-14 15:48 UTC, T-Syme commented
I'll implement Sandy's suggestions while I take care of [Adding a service as an admin](https://github.com/McGill-ECSE321-Winter2021/project-group-09/issues/94)

2021-03-14 16:02 UTC, T-Syme commented
Just a note before I forget: Javadoc should be added to the service methods in AdminService

2021-03-14 16:21 UTC, T-Syme commented
I'm not sure if I should be adding a method to add a service in the admin controller as I did or if there's a better way of doing it...

2021-03-14 16:58 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAdminService.java
> +
This has been resolved by https://github.com/McGill-ECSE321-Winter2021/project-group-09/pull/124/commits/2b4aeae8baa1dc9bbcbe185b50a1d075c1a383ae

2021-03-14 16:58 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAdminService.java
> +	}
This has been resolved by https://github.com/McGill-ECSE321-Winter2021/project-group-09/pull/124/commits/2b4aeae8baa1dc9bbcbe185b50a1d075c1a383ae

2021-03-14 16:59 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAdminService.java
> +			adminService.changeName("No One", "Some One");
This has been resolved by https://github.com/McGill-ECSE321-Winter2021/project-group-09/pull/124/commits/2b4aeae8baa1dc9bbcbe185b50a1d075c1a383ae

2021-03-14 17:00 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestAdminService.java
> +	public void testChangeNamelNull() {
This has been resolved by https://github.com/McGill-ECSE321-Winter2021/project-group-09/pull/124/commits/2b4aeae8baa1dc9bbcbe185b50a1d075c1a383ae

2021-03-14 17:04 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/AdminService.java
>  	@Transactional
This has been resolved by https://github.com/McGill-ECSE321-Winter2021/project-group-09/pull/124/commits/2b4aeae8baa1dc9bbcbe185b50a1d075c1a383ae

2021-03-14 18:08 UTC, sandyl289 reviewed
I'm not sure, but I think we don't need to put this in the AdminController since we already have this createService() in the ServiceController.

I'm looking at group 1's repo and it seems like they did not put the createAdvertisment() in [userController.java](https://github.com/McGill-ECSE321-Winter2020/project-group-01/blob/master/PetShelter-Backend/src/main/java/ca/mcgill/ecse321/petshelter/controller/UserController.java). They only have [createAdvertisement()](https://github.com/McGill-ECSE321-Winter2020/project-group-01/blob/22de27a9f1d9403489ffac559add113f7977bb5e/PetShelter-Backend/src/main/java/ca/mcgill/ecse321/petshelter/controller/AdvertisementController.java#L123-L147) in the AdvertisementController.java class. 


Their [use case diagram: ](https://github.com/McGill-ECSE321-Winter2020/project-group-01/wiki/Use-Case-Diagram#use-case-diagram)

![image](https://user-images.githubusercontent.com/70775435/111078958-49219880-84ce-11eb-9eb0-99acff48a5a8.png)

2021-03-14 18:09 UTC, sandyl289 approved these changes

2021-03-14 18:15 UTC, T-Syme commented
> I'm not sure, but I think we don't need to put this in the AdminController

Sounds good. I'll revert the last commit I added and close the [Adding a service as an admin](https://github.com/McGill-ECSE321-Winter2021/project-group-09/issues/94) issue separately

2021-03-14 19:42 UTC, JDziewonski98 approved these changes

2021-03-15 04:58 UTC, zhannaklimanova commented
@sandyl289 I'm not sure I understand why is it you removed the transactional part from adminToDto and other methods?

2021-03-15 13:33 UTC, T-Syme commented
@zhannaklimanova There are no transactions that occur when converting to an AdminDto (there's no interaction with the database). 
(If this isn't accurate, please correct me)

2021-03-15 20:09 UTC, merged