Please review these deletion methods
McGill-ECSE321-Winter2021/project-group-09 pull request #130
Opened 2021-03-15 12:05 UTC by zhannaklimanova

toString() methods added, 2 delete methods added to TechnicianService for code review; I will write test methods and implement those two delete methods in the controller after the general delete work schedule idea has been approved. Please look at the two methods that start with delete and let me know if I should change something , modify the deletion idea.

2021-03-15 13:19 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +		}
I'm not sure, but I think we'll need to:  (_I need a confirmation_)

- [x] Add `@AutowiredTimeSlotRepository timeSlotRepository;` to this class 
- [ ] Add `	timeSlotRepository.save(timeSlot);  ` in `addTechnicianWorkHours()`
- [ ] Delete all the appointments & timeslots by id (See suggested change)
![image](https://user-images.githubusercontent.com/70775435/111160897-ed5c1b80-8570-11eb-9abe-5cccd12707f5.png)



```suggestion
		// removing all the appointments
		for (Appointment appointmentToRemove: technician.getAppointments()) {
			appRepo.deleteById(appointmentToRemove.getAppointmentID());  //delete it from AppointmentRepository
			technician.getAppointments().remove(appointmentToRemove);
		}
		// removing all the timeslots
		for (TimeSlot timeSlotToRemove: technician.getTimeslots()) {
			timeSlotRepository.deleteById(timeSlotToRemove.getTimeSlotID()); //delete it from TimeSlot Repository
			technician.getTimeslots().remove(timeSlotToRemove);
		}
```

2021-03-15 13:29 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +			if (appointmentToDelete.getTimeSlot().equals(slotToDelete)) {
I believe that Java will check that this is the same object here, not that the start and end times are the same. In either case, I don't think that this does what the comment describes...
In order to remove all of the appointments within a given timeslot, you would need to check if the appointment start time is after the work hours start time (and ideally that the appointment end time is within the work hours too, but this should always be the case)

2021-03-15 13:29 UTC, T-Syme commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestTechnicianService.java
> +			System.out.println("tech schedule    " + timeSlots.toString());
Do we still need these print statements or can we remove them?

2021-03-15 13:35 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestTechnicianService.java
> +			System.out.println("tech schedule    " + timeSlots.toString());
I think you forgot to remove some print statements while debugging
```suggestion
```

2021-03-15 13:35 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestTechnicianService.java
> +			System.out.println("tech schedule 2    " + timeSlot.toString());
```suggestion
```

2021-03-15 14:02 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +				removedAppointments = true;
I think we'll need to add a  `break` statement right after finding the `appointment` to delete.

```suggestion
				removedAppointments = true;
				break;
```

2021-03-15 14:03 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +				removedTimeSlot = true;
We'll also need a  `break` statement right after finding the `timeslot`  to delete.

```suggestion
				removedTimeSlot = true;
				break;
```

2021-03-15 14:09 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +				technician.getAppointments().remove(appointmentToDelete);
I think we also need to remove it from the `AppointmentRepository appRepo`?
```suggestion
			if (appointmentToDelete.getTimeSlot().equals(slotToDelete)) {
			appRepo.deleteById(appointmentToRemove.getAppointmentID());  //delete it from AppointmentRepository
				technician.getAppointments().remove(appointmentToDelete);
```

2021-03-15 14:10 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +				technician.getTimeslots().remove(slotToDelete);
Here too, we need to add `timeSlotRepository.deleteById(timeSlotToRemove.getTimeSlotID())`?
```suggestion
			timeSlotRepository.deleteById(timeSlotToRemove.getTimeSlotID()); //delete it from TimeSlot Repository
				technician.getTimeslots().remove(slotToDelete);
```

2021-03-15 14:12 UTC, sandyl289 requested changes
I left some suggestions, but I'm not sure if they're right. 
If someone could verify them, that would be great! :)

2021-03-15 15:19 UTC, T-Syme commented
I'm not sure if it's necessary to remove them from the repos or not... Does the cascade from the relations between the tables take care of this?

2021-03-15 16:06 UTC, Shaswata79 approved these changes

2021-03-17 01:50 UTC, zhannaklimanova commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +				removedTimeSlot = true;
Well we want to remove all the appointments in a timeslot right? So if we need to remove all appointments, we need to go through the whole list without breaking.

2021-03-17 02:31 UTC, zhannaklimanova commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +				technician.getTimeslots().remove(slotToDelete);
In the case that the timeSlotId is null this will throw an exception which will cause the whole thing to crash. So I think it's best to remove the object

2021-03-17 11:31 UTC, Shaswata79 approved these changes

2021-03-17 20:52 UTC, T-Syme requested changes
I think that the tests in `TestTechnicianService` should be modified to check if the timeslots are actually being removed, not only that the return statement is equal.

Minor thing: are the print statements necessary or can they be removed now? (see comments above)

2021-03-17 20:52 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/TechnicianController.java
> +	@DeleteMapping("/delete/{email}")
I believe the mappings all need to be different (I'm not sure though)

`@DeleteMapping("/delete/{email}")` is already being used for deleting a technician, so I think we should rename this to `@DeleteMapping("/delete/hours/{email}")` or something like that

2021-03-17 20:52 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/TechnicianController.java
> +	@DeleteMapping("/delete/{email}")
Same thing here. I think we should rename this to `@DeleteMapping("/delete/schedule/{email}")` maybe?

2021-03-17 20:52 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +	public String deleteSpecificTechnicianTimeSlotAndAppointmentsFromSchedule(String email, java.sql.Timestamp startTimeSlot, java.sql.Timestamp endTimeSlot) throws Exception{
Could we shorten this method name to `deleteSpecificWorkHours()` or something like that? This seems a bit long for a method name...

2021-03-17 21:16 UTC, T-Syme commented
I don't think that the `deleteSpecificTechnicianTimeSlotAndAppointmentsFromSchedule()` method works as intended... From what I am seeing, the if statement in the outer for loop will return as soon as the timeslot is not equal, except that all of them are being looped through. I also think that the inner if statement is checking that the appointment start and end time are equal to the provided timeslot, except that that is a work hours timeslot.

I'm having a bit of trouble reading through it, so I'm going to try to rewrite it to go through the logic...

2021-03-17 21:46 UTC, T-Syme commented
I tried to go through the logic for `deleteSpecificTechnicianTimeSlotAndAppointmentsFromSchedule()` and this is what I came up with:

![image](https://user-images.githubusercontent.com/70815823/111542808-9446e000-8748-11eb-94f2-41acd6a22828.png)


The code in case anyone wants to copy and paste:
```
@Transactional 
	public String deleteSpecificTechnicianTimeSlotAndAppointmentsFromSchedule(String email, java.sql.Timestamp startTimeSlot, java.sql.Timestamp endTimeSlot) throws Exception {
		
		if (email == null || email.equals("")) throw new Exception("Email cannot be empty.");

		Technician technician = technicianRepository.findTechnicianByEmail(email);
		if (technician == null) throw new Exception("Technician not found.");

		List<TimeSlot> workHours = technician.getTimeslots();
		List<Appointment> appointments = technician.getAppointments();

		// Remove all appointments within timeslot and the timeslot itself
		for (TimeSlot hours : workHours) {
			// Find target timeslot
			if (hours.getStartDateTime().equals(startTimeSlot) && hours.getEndDateTime().equals(endTimeSlot)) {

				// Remove appointments in the work hours
				for (Appointment appointment : appointments) {
					TimeSlot appSlot = appointment.getTimeSlot();
					if (!hours.getStartDateTime().after(appSlot.getStartDateTime()) && !hours.getEndDateTime().before(appSlot.getEndDateTime())) {
						appointments.remove(appointment);
					}
				}

				// Remove timeslot
				workHours.remove(hours);
				technician.setTimeslots(workHours);
				technician.setAppointments(appointments);
				technicianRepository.save(technician);
				return "Requested TimeSlot and associate Appointments within the requested TimeSlot were removed.";
			}
		}
	
		return "Could not find provided work hours";
	}
```

2021-03-17 22:51 UTC, sandyl289 reviewed
I think we should refactor the method names

2021-03-17 22:51 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +	 *
```suggestion
	 * Deletes the whole work schedule of a technician

2021-03-17 22:51 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +	public String deleteSpecificTechnicianTimeSlotAndAppointmentsFromSchedule(String email, java.sql.Timestamp startTimeSlot, java.sql.Timestamp endTimeSlot) throws Exception{
I agree, I think we should make all the method names shorter and write the description of what the methods do in the javadoc instead to make our code more readable.

2021-03-18 02:03 UTC, sandyl289 commented
Tyler fixed the majority of the issues.

2021-03-18 02:03 UTC, merged