Added frontend pages View Appointment, View Technician Schedule and Modify Business Info
McGill-ECSE321-Winter2021/project-group-09 pull request #182
Opened 2021-03-25 15:50 UTC by Shaswata79

2021-03-25 19:49 UTC, T-Syme commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +                'date': thisApp.timeSlotDto.startDateTime.substring(0, 10),
There's a chance we'll need to change this to show the local time in the application. I'm not 100% sure, and I just wanted to make a note of this because I think I'm doing something similar to this

2021-03-25 19:51 UTC, T-Syme commented on RepairShop-Frontend/src/components/TopNavbar.vue
> +    <b-navbar-nav>
We can restrict which type of user sees these items later (Perfectly fine for now)

2021-03-25 19:52 UTC, T-Syme approved these changes

2021-03-25 22:24 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/ModifyBusinessInfo.vue
> +                numberOfRepairSpots: this.form.numRepairSpots
I have a feeling that what this will do, if the user only updates one field, for example email, it will overwrite all other fields with an empty string, but I didn't test it... Have you made sure it works correctly?

2021-03-25 22:26 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +        var appointments = tempAppList.map(thisApp => {
This doesn't work for me, tempAppList is still undefined. This is because the axios call you send above is asynchronous, so this line may execute before like 61 'tempAppList = response.data' has happened. Any logic that depends on the axios response should go into the .then().

2021-03-25 22:29 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +    <p></p>
style the divs above or below with a margin instead of making empty \<p\> tags to add space

2021-03-25 22:31 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +        var url = LOCALHOST_BACKEND + "api/technician/" + email + "/appointments";
url doesn't work, needs / before api

2021-03-25 22:32 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianSchedule.vue
> +        var url = LOCALHOST_BACKEND + "api/technician/" + email + "/schedule";
missing '/' in url

2021-03-25 22:34 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianSchedule.vue
> +      <b-form-group id="input-group-2" label="Enter a date:" label-for="input-1">
should definitely do some sort of user input restriction: force a specific format or generate valid data in form of a dropdown or something

2021-03-25 22:35 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TopNavbar.vue
> +    <b-navbar-nav>
do a v-show="this.$root.$data.userType === 'Admin'" I think

2021-03-25 22:50 UTC, JDziewonski98 requested changes
Good start, left comments that will hopefully be useful towards getting it complete, couldn't quite test all the logic because im getting some runtime errors / backend urls aren't correct

2021-03-26 01:10 UTC, sandyl289 reviewed
I agree with Jacek and left some minor suggestions. I wasn't able to tests the pages. Good work though! 👍🏼

2021-03-26 01:10 UTC, sandyl289 commented on RepairShop-Frontend/src/components/ModifyBusinessInfo.vue
> +      </b-form-group>
I wonder if there's a way to prefill all the current information

2021-03-26 01:10 UTC, sandyl289 commented on RepairShop-Frontend/src/components/ModifyBusinessInfo.vue
> +    <b-form @submit="onSubmit">
```suggestion
<h1>Modify Business Information</h1>
    <b-form @submit="onSubmit">
```

2021-03-26 01:10 UTC, sandyl289 commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +
```suggestion
<h1>All Technician's Appointments</h1>
```

2021-03-26 14:29 UTC, Shaswata79 commented on RepairShop-Frontend/src/components/ModifyBusinessInfo.vue
> +                numberOfRepairSpots: this.form.numRepairSpots
The backend throws an error if any of the fields are null. So I made the inputs "required" for now. That should prevent overwriting existing fields with empty strings right? I'll look into how to make the fields pre-filled.

2021-03-26 14:42 UTC, T-Syme commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +                'date': thisApp.timeSlotDto.startDateTime.substring(0, 10),
Here's the function I used to display the local time: 
```
displayDateTime(dateTime) {
    let date = new Date(dateTime).toString(); // Should output something like "Tue Mar 02 2021 10:00:00 GMT-0500 (Eastern Standard Time)"
    if (date == "Invalid Date") return '';
    else return date.slice(0, 10) + ", " + date.slice(11, 15) + " at " + date.slice(16, 21);
}
```

For example, it would take in "2021-03-02T15:00:00.000+00:00" and convert it to "Tue Mar 02, 2021 at 10:00" for my time zone.

This is only to show it to the user though. It should probably still be stored as a Timestamp in the app

2021-03-26 19:00 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/ModifyBusinessInfo.vue
> +                numberOfRepairSpots: this.form.numRepairSpots
Maybe the backend can be changed so that it accepts null values and only updates what is not null. Haven't looked at the backend code tho

2021-03-26 19:02 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/ModifyBusinessInfo.vue
> +      </b-form-group>
if you call the get business info on component mount, you can then prefill it with the response data

2021-03-27 14:57 UTC, sandyl289 reviewed
Keep up with the good work! 👍🏼 

- I think it would be nice to also display the `dates`
![image](https://user-images.githubusercontent.com/70775435/112723827-e2957500-8ee6-11eb-9888-c40176d0f75e.png)

- We'll have to remove the duplicates before merging to `main`
![image](https://user-images.githubusercontent.com/70775435/112723796-b5e15d80-8ee6-11eb-9a16-ca7e922e9c1a.png)

- I think we can remove "Form Data Result"
![image](https://user-images.githubusercontent.com/70775435/112724653-c5fb3c00-8eea-11eb-9816-35c46415cb88.png)

2021-03-28 01:00 UTC, T-Syme approved these changes
I agree with Sandy's suggestions. Looks good!

2021-03-28 01:54 UTC, JDziewonski98 commented
> Keep up with the good work! 👍🏼
> 
> * I think it would be nice to also display the `dates`
>   ![image](https://user-images.githubusercontent.com/70775435/112723827-e2957500-8ee6-11eb-9888-c40176d0f75e.png)
> * We'll have to remove the duplicates before merging to `main`
>   ![image](https://user-images.githubusercontent.com/70775435/112723796-b5e15d80-8ee6-11eb-9a16-ca7e922e9c1a.png)
> * I think we can remove "Form Data Result"
>   ![image](https://user-images.githubusercontent.com/70775435/112724653-c5fb3c00-8eea-11eb-9816-35c46415cb88.png)

I agree with displaying the dates, Tyler wrote a function to turn a timestamp into a nicely formatted string, examples of how it can be used are in ViewAppointment or BookAppointment

2021-03-28 19:29 UTC, T-Syme commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestBusinessService.java
> +    */
We'll just have to remember to remove all of the commented tests later...

Should new tests be added to check if a business can be updated with empty values now?

2021-03-29 05:48 UTC, JDziewonski98 requested changes
Left some comments after running and reading the code
tested using the root admin and technician: techboi@mail.com with password 'password'

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianSchedule.vue
> +    <h1>Weekly schedule</h1>
Should center this

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianScheduleAdmin.vue
> +    <h1>Technician's weekly schedule</h1>
Should center this

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianScheduleAdmin.vue
> +        var url = LOCALHOST_BACKEND + "/api/technician/" + this.techEmail + "/schedule";
You need to add the line 'event.preventDefault();' or else the page will refresh upon submit, which will also log you out

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianScheduleAdmin.vue
> +
spacing is awkward

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianScheduleAdmin.vue
> +            console.log(error.response.data);
gotta add some sort of visual prompt that email is invalid

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianScheduleAdmin.vue
> +
You can get an auto formatter extension in Vscode like 'prettier' that should handle stuff like that on file save

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianScheduleAdmin.vue
> +      <b-table :fields="fields" :items="items" responsive="sm">
![image](https://user-images.githubusercontent.com/46234488/112790468-3e115100-9014-11eb-9749-98d73f124379.png)
"index" is irrelevant information to display, maybe ID would be better or nothing at all

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianScheduleAdmin.vue
> +    <b-card class="mt-3" header="Message">
I think you should just make some red text appear with an error message rather than this message box to keep it consistent with other pages

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TopNavbar.vue
> +      </b-nav-item>
gotta get rid of duplicate elements in navbar pls 
![image](https://user-images.githubusercontent.com/46234488/112791073-97c64b00-9015-11eb-8ffd-d500f692e310.png)

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianScheduleAdmin.vue
> +          <label for="schedule-datepicker">Choose a date</label>
This is really awkward, as we want to pick a week, and here we are given the choice of an individual day, which will still return schedule for the entire week. IMO a quick way to ameliorate this would be to disable choosing anything except a Monday (representing the start of a week), just modify this example from the component doc page
![image](https://user-images.githubusercontent.com/46234488/112791404-5a15f200-9016-11eb-8d00-e7b1e737cd3d.png)

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianSchedule.vue
> +<template>
Basically same comments as TechnicianScheduleAdmin

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +<template>
I think could be easier to just copy paste my code for view customer appointments page from main if this isn't ready yet, I could do it quick probably

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/ModifyBusinessInfo.vue
> +    <b-card class="mt-3" header="Message">
I think this box thing should be removed

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/ModifyBusinessInfo.vue
> +            this.message = "";
add 'event.preventDefault();' to prevent page refresh

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/ModifyBusinessInfo.vue
> +      <b-form-group id="input-group-1" label="Email address:" label-for="input-1">
It's a bit awkward modifying the business info without seeing what it is right now, I think there should be a create() method that gets the business info and displays it above each bar at least, better solution would be to integrate the modify info into the view info page if logged in as admin but it's fine

2021-03-29 05:48 UTC, JDziewonski98 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestBusinessService.java
> +    */
the project description says that our backend will still be evaluated for this deliverable so I think the tests should be updated so we still maintain 90% coverage

2021-03-29 06:08 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianScheduleAdmin.vue
> +          <label for="tech-email">Enter technician's email</label>
Would be cool if you do a get all technicians request during component creation and make this a drop down populated by all technician emails

2021-03-29 10:52 UTC, Shaswata79 commented
Made the changes Jacek suggested. Didn't change anything in View appointments though.

2021-03-29 16:06 UTC, sandyl289 reviewed
- Really nice! I like how we can see a list of technicians for `Technician's Weekly Schedule` 💯 👍🏼 
 
![image](https://user-images.githubusercontent.com/70775435/112858579-017b3f00-9080-11eb-8163-1c86e3ba5e2b.png)

- It's fine as it is now, but if we have time, it would be nice to display a message to indicate that there's no work on that week. 

![image](https://user-images.githubusercontent.com/70775435/112858838-43a48080-9080-11eb-8fca-e60d1a4b6e60.png)

# Testing

## Technician's weekly schedule (Admin)
(EDIT: Everything works 💯 )

## Technician Appointments (Technician `techboi@mail.com`) This seems to work 💯 
- (Please ignore this:) Really not important, but it would be nice to also have the customer's name displayed here
![image](https://user-images.githubusercontent.com/70775435/112863784-363dc500-9085-11eb-9f81-be11862bb4c3.png)

2021-03-29 16:06 UTC, sandyl289 commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +        <div v-if="errorViewServices">
Really not important, but we should change the error's name to `errorViewAppointments` if we have time😄

2021-03-29 16:53 UTC, Shaswata79 commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +        <div v-if="errorViewServices">
That's weird. When I try to get the appointments for techboi@mail.com on the week of March 22, it gives me no errors. The schedule is correctly shown.

2021-03-29 17:05 UTC, sandyl289 commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +        <div v-if="errorViewServices">
# It works fine!! It's just my computer 😅 Sorry about that!
![image](https://user-images.githubusercontent.com/70775435/112873192-4f4b7380-908f-11eb-9812-7255029229ae.png)

2021-03-29 17:42 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/TechnicianAppointments.vue
> +        <div v-if="errorViewServices">
Haven't ran it after the changes, but from the screenshots I see the red error message, I don't think it should output the entire json data, just display a readable message like "Something went wrong.". And for weekly schedule I still think we should remove the index column.

2021-04-02 14:24 UTC, merged