addHoliday reiview changes  pleaase
McGill-ECSE321-Winter2021/project-group-09 pull request #190
Opened 2021-03-29 00:53 UTC by zhannaklimanova

2021-03-29 03:18 UTC, T-Syme approved these changes

2021-03-29 06:16 UTC, JDziewonski98 requested changes
add holiday seems good to go other than a minor issue
maybe look at view customer appointments on main to see how to fetch a list of data and populate a table for view holidays

2021-03-29 06:16 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/AddHoliday.vue
> +      event.preventDefault();
should add a simple check to make sure end date is after start date
![image](https://user-images.githubusercontent.com/46234488/112794104-373a0c80-901b-11eb-93ef-8845d70e9175.png)

2021-03-29 06:16 UTC, JDziewonski98 commented on RepairShop-Frontend/src/components/AddHoliday.vue
> +  <div id="addHolidayForm">
Would be good to center the entire page (could wrap everything in a div and play with centering css)
![image](https://user-images.githubusercontent.com/46234488/112794258-71a3a980-901b-11eb-9150-ba3b0daef384.png)

2021-03-29 14:47 UTC, Shaswata79 approved these changes

2021-03-29 14:58 UTC, sandyl289 approved these changes
I agree with Jacek's comments. I saw that you created a blank page for View Holidays. Are you going to create a separate page for "View Holidays"?

- All tests pass (Repository & Service)
- Everything seems to work perfectly  💯 👍🏼 

# Testing
## Adding Holiday (After logging in as Admin)
![image](https://user-images.githubusercontent.com/70775435/112855954-54072c00-907d-11eb-9bf6-fc5e9254a4b8.png)

## From Postman (Get All Holidays)
![image](https://user-images.githubusercontent.com/70775435/112856142-7b5df900-907d-11eb-90b9-b20aee1ddb43.png)

2021-03-30 20:41 UTC, zhannaklimanova commented on RepairShop-Frontend/src/components/AddHoliday.vue
> +      event.preventDefault();
ok, I'll look into it

2021-03-30 20:43 UTC, zhannaklimanova commented
> I agree with Jacek's comments. I saw that you created a blank page for View Holidays. Are you going to create a separate page for "View Holidays"?
> 
> * All tests pass (Repository & Service)
> * Everything seems to work perfectly  💯 👍🏼
> 
> # Testing
> ## Adding Holiday (After logging in as Admin)
> ![image](https://user-images.githubusercontent.com/70775435/112855954-54072c00-907d-11eb-9bf6-fc5e9254a4b8.png)
> 
> ## From Postman (Get All Holidays)
> ![image](https://user-images.githubusercontent.com/70775435/112856142-7b5df900-907d-11eb-90b9-b20aee1ddb43.png)

@sandyl289 Yea, so Tyler and I were talking about it and he said that you're working on  the  display holidays page and that I should move on to viewing/deleting appointments for technicians from the admin account. But If you would like, I can try doing the display holiday thing.

2021-03-31 03:38 UTC, sandyl289 commented
> > I agree with Jacek's comments. I saw that you created a blank page for View Holidays. Are you going to create a separate page for "View Holidays"?
> > 
> > * All tests pass (Repository & Service)
> > * Everything seems to work perfectly  💯 👍🏼
> > 
> > # Testing
> > ## Adding Holiday (After logging in as Admin)
> > ![image](https://user-images.githubusercontent.com/70775435/112855954-54072c00-907d-11eb-9bf6-fc5e9254a4b8.png)
> > ## From Postman (Get All Holidays)
> > ![image](https://user-images.githubusercontent.com/70775435/112856142-7b5df900-907d-11eb-90b9-b20aee1ddb43.png)
> 
> @sandyl289 Yea, so Tyler and I were talking about it and he said that you're working on the display holidays page and that I should move on to viewing/deleting appointments for technicians from the admin account. But If you would like, I can try doing the display holiday thing.

- The admin can view holidays on the `Holidays: View & Delete` page, so I guess we don't need a separate page now.
![image](https://user-images.githubusercontent.com/70775435/113087420-92056c80-91b1-11eb-86dc-4bdd2571ce05.png)

- As for everyone, they can see the holidays on the `Contact Us` page now 
![image](https://user-images.githubusercontent.com/70775435/113087197-1efbf600-91b1-11eb-9a7b-512437f30b2d.png)

2021-03-31 04:01 UTC, sandyl289 reviewed
- We should remove `ViewHolidays.vue` before merging to `main`
- & remove it from TopNavBar.vue (see [commit suggestion](https://github.com/McGill-ECSE321-Winter2021/project-group-09/pull/190#discussion_r604573418) )

# Testing `Add New Holidays` page 

## 1) POSTMAN (See current holidays)
![image](https://user-images.githubusercontent.com/70775435/113087975-b0b83300-91b2-11eb-87d1-9b59e39e2198.png)

## 2) Add New Holiday

### 2A) TEST invalid start date before end date ⚠️
- I agree with Jacek, I think it would be great if we have something to make sure that the `start date` is before the `end date` + error message  ⚠️
![image](https://user-images.githubusercontent.com/70775435/113088148-0a206200-91b3-11eb-9a82-d68380fe5ab1.png)

### 2B) TEST valid dates ✔️
![image](https://user-images.githubusercontent.com/70775435/113088514-b82c0c00-91b3-11eb-9ff0-628b6319a37f.png)

##  3) POSTMAN (Make sure holidays were added correctly) ✔️
![image](https://user-images.githubusercontent.com/70775435/113088648-0b9e5a00-91b4-11eb-8638-c9253e6723ee.png)

2021-03-31 04:01 UTC, sandyl289 commented on RepairShop-Frontend/src/components/TopNavbar.vue
> +      <b-nav-item to="ViewHolidays">View Holidays</b-nav-item>
We can delete this before merging to `main`
```suggestion
```

2021-04-02 13:56 UTC, sandyl289 commented on RepairShop-Frontend/src/components/AddHoliday.vue
> +  <div id="addHolidayForm">
Will do this later after merging all branches

2021-04-02 14:00 UTC, sandyl289 commented on RepairShop-Frontend/src/components/TopNavbar.vue
> +      <b-nav-item to="ViewHolidays">View Holidays</b-nav-item>
done!

2021-04-02 14:02 UTC, merged