Technician and Customer service tests completed. All tests passing so far.
McGill-ECSE321-Winter2021/project-group-09 pull request #73
Opened 2021-03-04 16:38 UTC by Shaswata79

2021-03-04 18:32 UTC, T-Syme requested changes
In the service files we might want to change the if statements to include empty strings like this:
if (email == null || email.equals("") || password == null || password.equals(""))  

Could Javadoc please be added to the REST endpoints?

2021-03-04 18:32 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/TimeSlotDto.java
> +
Why is this all commented out?

2021-03-04 20:35 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +	public TechnicianDto createTechnician(String email, String password, String phone, String name, String address) throws Exception{
Should this method return a Technician instead of a TechnicianDto? I'm not sure if we're following the tutorial exactly, but they return the regular object here. It's in section 2.8.1 of the tutorial notes or you can search for "public Person createPerson(String name)"

2021-03-04 22:16 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +	public TechnicianDto createTechnician(String email, String password, String phone, String name, String address) throws Exception{
I did the same thing as Shaswata
I'm following Group 1's [ UserService class](https://github.com/McGill-ECSE321-Winter2020/project-group-01/blob/22de27a9f1d9403489ffac559add113f7977bb5e/PetShelter-Backend/src/main/java/ca/mcgill/ecse321/petshelter/service/UserService.java#L74) example.

2021-03-05 00:02 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +	public TechnicianDto changePassword(String email, String newPassword) throws Exception{
I think it's good enough, but something to possibly consider is to take in string oldpassword so that they have to type in their current password and the password they want to change it to

2021-03-05 00:06 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/TechnicianController.java
> +	@PostMapping(value = { "/technician/register", "/technician/register/" })
why (value = { "/technician/register", "/technician/register/" } ?
It should be enough to do @PostMapping( "/technician/register")

2021-03-05 00:08 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/TechnicianController.java
> +@RestController
should put a @RequestMapping("/api/technician") here, it will apply to all methods in the class

2021-03-05 00:08 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/TechnicianController.java
> +	@PostMapping(value = { "/technician/register", "/technician/register/" })
Considering my above comment, can jsut be @PostMapping( "/register")

2021-03-05 00:11 UTC, JDziewonski98 approved these changes
good work, one nitpick about how your @Request/Post/whatever/mappings were structured, but maybe i'm missing something

2021-03-05 00:16 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +	public TechnicianDto createTechnician(String email, String password, String phone, String name, String address) throws Exception{
I think if we convert to DTO in controller or service class is up to us as long as we keep it consistent

2021-03-05 00:19 UTC, JDziewonski98 reviewed
One more thing... I saw that you didnt actually add password to the Models. Do you want to try adding a @NotNull string password field to the model classes, reset the database in heroku, and fix up the persistence tests? (You will likely jsut have to add a password to each customer / tech that is created in the tests, since it should be a @NotNull field)

2021-03-05 01:08 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/TechnicianService.java
> +	public TechnicianDto createTechnician(String email, String password, String phone, String name, String address) throws Exception{
I agree, I decided to follow what you guys did

2021-03-05 01:10 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/CustomerController.java
> +@CrossOrigin(origins = "*")
```suggestion
@CrossOrigin(origins = "*")
@RequestMapping("/api/Customer")
```

2021-03-05 01:17 UTC, sandyl289 reviewed
Other than what Jacek said, it seems like everything is good!

2021-03-05 05:55 UTC, merged