Service dtos, services and controller (all tests pass)
McGill-ECSE321-Winter2021/project-group-09 pull request #97
Opened 2021-03-05 15:48 UTC by T-Syme

2021-03-05 17:11 UTC, Shaswata79 approved these changes

2021-03-06 04:15 UTC, JDziewonski98 approved these changes
LGTM

2021-03-06 15:00 UTC, sandyl289 requested changes
I added some  tests suggestion  for getServiceByName and getAllServices().
Other than that, I think we are ready to merge it to the main branch! 💯

2021-03-06 15:00 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestServiceService.java
> +
```suggestion
    @Test
    public void testGetAllServices() {

        List<ServiceDto> serviceDtos = serviceService.getAllServices();
        assertEquals(1, serviceDtos.size()); // List contains a single element.
        ServiceDto serviceDto = (ServiceDto) serviceDtos.toArray()[0];
        assertEquals(SERVICE_NAME, serviceDto.getName()); // List contains the only comment.
        assertEquals(SERVICE_DURATION, serviceDto.getDuration()); // List contains the only comment.
        assertEquals(SERVICE_PRICE, serviceDto.getPrice()); // List contains the only comment.
        
    }
```

2021-03-06 15:00 UTC, sandyl289 commented on RepairShop-Backend/src/test/java/ca/mcgill/ecse321/repairshop/service/TestServiceService.java
> +    }
```suggestion
    @Test //valid service name
    public void testServiceByName() {
        ServiceDto serviceDto = null;
        try{
            serviceDto = serviceService.getServiceByName(SERVICE_NAME);

        } catch (Exception e) {
            fail(e.getMessage());
        }
        
        assertNotNull(serviceDto);
        assertEquals(SERVICE_NAME, serviceDto.getName());
        assertEquals(SERVICE_DURATION, serviceDto.getDuration());
        assertEquals(SERVICE_PRICE, serviceDto.getPrice());
    }
    
        @Test //invalid service name
    public void testServiceByNameNonExistent() {
        String error=null;
        ServiceDto serviceDto = null;
        String name = "I don't exist";
        try{
            serviceDto = serviceService.getServiceByName(name);

        } catch (Exception e) {
            error = e.getMessage();
        }

        assertNull(serviceDto);
        assertEquals("Could not find service with name "+name, error);
    }
    }
```

2021-03-06 15:09 UTC, sandyl289 commented
I'm not sure if we should link this pull request to the [Add service (Admin)](https://github.com/McGill-ECSE321-Winter2021/project-group-09/issues/94), since closing this pull request will also close that issue. 
The "Add service (Admin)"  issue is not complete yet, since we'll need to verify that the user logged in is the Admin.

![image](https://user-images.githubusercontent.com/70775435/110211172-610c7300-7e63-11eb-89d3-c6d79f967a92.png)

2021-03-06 15:25 UTC, T-Syme commented
> I'm not sure if we should link this pull request to the [Add service (Admin)](https://github.com/McGill-ECSE321-Winter2021/project-group-09/issues/94), since closing this pull request will also close that issue.
> The "Add service (Admin)" issue is not complete yet, since we'll need to verify that the user logged in is the Admin.

You're right, thanks!

2021-03-06 16:04 UTC, sandyl289 approved these changes
I think we can merge it to master now

2021-03-07 01:32 UTC, merged