Completed everything for reminders (tests passing)
McGill-ECSE321-Winter2021/project-group-09 pull request #99
Opened 2021-03-05 19:11 UTC by T-Syme

2021-03-06 04:00 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/controller/ReminderController.java
> +            return new ResponseEntity<>(reminderService.getRemindersByCustomer(customerRepository.findCustomerByEmail(email)), HttpStatus.OK);
repositories should not be used in the controller level, db operations should be done only at service level (that is just the convention of the controller / service split )

2021-03-06 04:01 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/ReminderDto.java
> +    private Customer customer;
should be customerdto type (otherwise a reminder dto will show the password of the user)

2021-03-06 04:01 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/service/ReminderService.java
> +        reminderDto.setCustomer(reminder.getCustomer());
should convert the customer to a dto

2021-03-06 04:03 UTC, JDziewonski98 requested changes
Left 2 main remarks that are easy to miss but IMO important, otherwise looks good

2021-03-06 13:39 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/ReminderDto.java
> +    private Customer customer;
Right, sounds good. That'll also let me use the service instead of the repository (in the previous comment)

2021-03-06 14:54 UTC, T-Syme commented
The changes were made that @JDziewonski98 suggested. If they can be reviewed, that would be great

2021-03-06 15:59 UTC, sandyl289 requested changes
Some additional tests needed, other than it looks good! + _I wrote some questions to ask Jacek._

2021-03-06 15:59 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/ReminderDto.java
> +
```suggestion
private Long reminderID;
```

2021-03-06 15:59 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/dto/ReminderDto.java
> +
```suggestion
    public long getReminderID() {
        return this.reminderID;
    }

    public void setReminderID(long reminderID) {
        this.reminderID = reminderID;
    }
```

2021-03-06 15:59 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/model/Reminder.java
> -	}
**Questions:**

**1.** @JDziewonski98 Since the IDs are autogenerated, do we need a `setReminderID(Long reminderID)`  method in the model class?

**2.**  I noticed you have some parameters for `@GeneratedValue(strategy = GenerationType.AUTO)` in your [TimeSlot.java model class](https://github.com/McGill-ECSE321-Winter2021/project-group-09/blob/c3725b01b5fb25934699a8dd07380b6f3cb9b09d/RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/model/TimeSlot.java#L11-L17) , do we need to add that to all classes that have an ``@GeneratedValue`` ?

2021-03-06 16:47 UTC, T-Syme commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/model/Reminder.java
> -	}
I added it back just in case we need it

2021-03-07 06:13 UTC, Shaswata79 approved these changes

2021-03-07 08:13 UTC, JDziewonski98 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/model/Reminder.java
> -	}
1. Not sure, i'd just leave it
2. I think AUTO is the default so it should be fine without it

2021-03-07 08:14 UTC, JDziewonski98 approved these changes
looks good to merge (I suggest selecting 'squash and merge')

2021-03-07 14:02 UTC, sandyl289 approved these changes

2021-03-07 14:12 UTC, sandyl289 commented on RepairShop-Backend/src/main/java/ca/mcgill/ecse321/repairshop/model/Reminder.java
> -	}
Thanks Jacek!

2021-03-07 16:04 UTC, T-Syme commented
The ReminderController is using only Strings as inputs now. All corresponding methods were updated and more tests were written for input validation

2021-03-07 16:41 UTC, sandyl289 approved these changes
(Not important) I wrote some suggestions to change some error messages (customer->customer email) and the name of a method.
See pull request #108 .

2021-03-07 23:19 UTC, merged